gas optimization to MerkleMultiProof
polytope-labs/solidity-merkle-trees pull request #4
Opened 2023-01-23 09:40 UTC by nuel-ikwuoma

added some gas optimization specific to EVM to MerkleMultiProof.sol
these changes should reduce the gas cost for calling the verifyProof routine

2023-01-23 10:55 UTC, samparsky requested changes

2023-01-23 10:55 UTC, samparsky commented on lib/MerkleMultiProof.sol
> +        external
change this to internal. To make the tests pass create a `contract` instead that uses the library

2023-01-23 17:16 UTC, seunlanlege approved these changes
Lgtm

2023-01-23 17:26 UTC, seunlanlege commented
@nuel-ikwuoma you'll need to implement commit signing on your local git config & sign your commits. See https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2023-01-23 17:27 UTC, seunlanlege commented
Then force push the newly signed commits

2023-01-23 18:39 UTC, nuel-ikwuoma commented
@seunlanlege commit is verified

2023-01-23 20:16 UTC, seunlanlege commented
> @seunlanlege commit is verified

All commits have to be verified

2023-01-24 04:09 UTC, seunlanlege commented
Tested locally and saw some gas reductions, nothing too major.

2023-01-24 04:09 UTC, merged